Revert "lit: revert be49a11debf15b109371e5cfd361dffabefc83c5"
This reverts commit f85ac4dee6fa9c0b518f9184cf1b60bd8bd540a2.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74